In [3]:
import sqlite3
import json
from datetime import datetime

timeframe = '2018-05'
sql_transaction = []
start_row = 0
cleanup = 1000000

connection = sqlite3.connect('{}.db'.format(timeframe))
c = connection.cursor()

def create_table():
    c.execute("CREATE TABLE IF NOT EXISTS parent_reply(parent_id TEXT PRIMARY KEY, comment_id TEXT UNIQUE, parent TEXT, comment TEXT, subreddit TEXT, unix INT, score INT)""")


# as if cleaning    
def format_data(data):
    data = data.replace("\n"," newlinechar ").replace("\r", " newlinechar ").replace('"',"'")
    return data

def find_parent(pid):
    try:
        sql = "SELECT comment FROM parent_reply WHERE comment_id = '{}' LIMIT 1".format(pid)
        c.execute(sql)
        result = c.fetchone()
        if result != None:
            return result[0]
        else: 
            return False
    except Exception as e:
#         print("find_parent", e)
        return False

def find_existing_score(pid):
    try:
        sql = "SELECT score FROM parent_reply WHERE parent_id = '{}' LIMIT 1".format(pid)
        c.execute(sql)
        result = c.fetchone()
        if result != None:
            return result[0]
        else: 
            return False
    except Exception as e:
#         print("find_parent", e)
        return False    

def acceptable(data):
    if len(data.split(' ')) > 50 or len(data) < 1:
        return False
    elif len(data) > 1000:
        return False
    elif data == '[deleted]' or data == '[removed]':
        return False
    else:
        return True
    
def transaction_bldr(sql):
    global sql_transaction
    sql_transaction.append(sql)
    if len(sql_transaction) > 1000:
        c.execute('BEGIN TRANSACTION')
        for s in sql_transaction:
            try:
                c.execute(s)
            except:
                pass
        connection.commit()
        sql_transaction = []
    
def sql_insert_replace_comment(commentid,parentid,parent,comment,subreddit,time,score):
    try:
        sql = """UPDATE parent_reply SET parent_id = ?, comment_id = ?, parent = ?, comment = ?, subreddit = ?, unix = ?, score = ? WHERE parent_id =?;""".format(parentid, commentid, parent, comment, subreddit, int(time), score, parentid)
        transaction_bldr(sql)
    except Exception as e:
        print('s-UPDATE',str(e))

def sql_insert_has_parent(commentid,parentid,parent,comment,subreddit,time,score):
    try:
        sql = """INSERT INTO parent_reply (parent_id, comment_id, parent, comment, subreddit, unix, score) VALUES ("{}","{}","{}","{}","{}",{},{});""".format(parentid, commentid, parent, comment, subreddit, int(time), score)
        transaction_bldr(sql)
    except Exception as e:
        print('s-PARENT',str(e))

def sql_insert_no_parent(commentid,parentid,comment,subreddit,time,score):
    try:
        sql = """INSERT INTO parent_reply (parent_id, comment_id, comment, subreddit, unix, score) VALUES ("{}","{}","{}","{}",{},{});""".format(parentid, commentid, comment, subreddit, int(time), score)
        transaction_bldr(sql)
    except Exception as e:
        print('s-NO PARENT',str(e))

In [4]:
if __name__ == "__main__":
    create_table()
    row_counter = 0
    paired_rows = 0
        
    with open("/media/muhammad/New Volume/Data/reddit_data/{}/RC_{}".format(timeframe.split('-')[0], timeframe), buffering = 1000) as f:
        for row in f:
            #print(row)
            #time.sleep(555)
            row_counter += 1

            if row_counter > start_row:
                try:
                    row = json.loads(row)
                    parent_id = row['parent_id'].split('_')[1]
                    body = format_data(row['body'])
                    created_utc = row['created_utc']
                    score = row['score']
                    
                    comment_id = row['id']
                    
                    subreddit = row['subreddit']
                    parent_data = find_parent(parent_id)
                    
                    existing_comment_score = find_existing_score(parent_id)
                    if existing_comment_score:
                        if score > existing_comment_score:
                            if acceptable(body):
                                sql_insert_replace_comment(comment_id,parent_id,parent_data,body,subreddit,created_utc,score)
                                
                    else:
                        if acceptable(body):
                            if parent_data:
                                if score >= 2:
                                    sql_insert_has_parent(comment_id,parent_id,parent_data,body,subreddit,created_utc,score)
                                    paired_rows += 1
                            else:
                                sql_insert_no_parent(comment_id,parent_id,body,subreddit,created_utc,score)
                except Exception as e:
                    print(str(e))
                            
            if row_counter % 100000 == 0:
                print('Total Rows Read: {}, Paired Rows: {}, Time: {}'.format(row_counter, paired_rows, str(datetime.now())))

            if row_counter > start_row:
                if row_counter % cleanup == 0:
                    print("Cleanin up!")
                    sql = "DELETE FROM parent_reply WHERE parent IS NULL"
                    c.execute(sql)
                    connection.commit()
                    c.execute("VACUUM")
                    connection.commit()

Total Rows Read: 100000, Paired Rows: 4501, Time: 2018-08-08 17:03:27.908841
Total Rows Read: 200000, Paired Rows: 10741, Time: 2018-08-08 17:03:37.550652
Total Rows Read: 300000, Paired Rows: 17267, Time: 2018-08-08 17:03:46.722817
Total Rows Read: 400000, Paired Rows: 24291, Time: 2018-08-08 17:03:56.167579
Total Rows Read: 500000, Paired Rows: 31644, Time: 2018-08-08 17:04:05.939044
Total Rows Read: 600000, Paired Rows: 39252, Time: 2018-08-08 17:04:15.671682
Total Rows Read: 700000, Paired Rows: 47138, Time: 2018-08-08 17:04:25.099246
Total Rows Read: 800000, Paired Rows: 54482, Time: 2018-08-08 17:04:34.616275
Total Rows Read: 900000, Paired Rows: 61689, Time: 2018-08-08 17:04:44.359417
Total Rows Read: 1000000, Paired Rows: 68761, Time: 2018-08-08 17:04:54.014423
Cleanin up!
Total Rows Read: 1100000, Paired Rows: 73618, Time: 2018-08-08 17:05:07.053839
Total Rows Read: 1200000, Paired Rows: 79675, Time: 2018-08-08 17:05:16.407508
Total Rows Read: 1300000, Paired Rows: 86673, Time: 2018-08-08 17:05:26.283999
Total Rows Read: 1400000, Paired Rows: 94112, Time: 2018-08-08 17:05:36.162462
Total Rows Read: 1500000, Paired Rows: 101935, Time: 2018-08-08 17:05:45.774689
Total Rows Read: 1600000, Paired Rows: 110014, Time: 2018-08-08 17:05:55.544515
Total Rows Read: 1700000, Paired Rows: 118224, Time: 2018-08-08 17:06:05.366675
Total Rows Read: 1800000, Paired Rows: 126639, Time: 2018-08-08 17:06:14.875510
Total Rows Read: 1900000, Paired Rows: 135329, Time: 2018-08-08 17:06:24.351649
Total Rows Read: 2000000, Paired Rows: 143883, Time: 2018-08-08 17:06:33.853382
Cleanin up!
Total Rows Read: 2100000, Paired Rows: 149708, Time: 2018-08-08 17:06:47.309635
Total Rows Read: 2200000, Paired Rows: 157349, Time: 2018-08-08 17:06:57.762813
Total Rows Read: 2300000, Paired Rows: 165130, Time: 2018-08-08 17:07:07.887388
Total Rows Read: 2400000, Paired Rows: 173335, Time: 2018-08-08 17:07:17.449197
Total Rows Read: 2500000, Paired Rows: 181471, Time: 2018-08-08 17:07:27.080213
Total Rows Read: 2600000, Paired Rows: 189631, Time: 2018-08-08 17:07:36.743431
Total Rows Read: 2700000, Paired Rows: 197584, Time: 2018-08-08 17:07:46.326230
Total Rows Read: 2800000, Paired Rows: 205470, Time: 2018-08-08 17:07:55.800823
Total Rows Read: 2900000, Paired Rows: 213975, Time: 2018-08-08 17:08:05.285383
Total Rows Read: 3000000, Paired Rows: 222610, Time: 2018-08-08 17:08:15.005364
Cleanin up!
Total Rows Read: 3100000, Paired Rows: 228667, Time: 2018-08-08 17:08:29.958534
Total Rows Read: 3200000, Paired Rows: 236142, Time: 2018-08-08 17:08:39.225948
Total Rows Read: 3300000, Paired Rows: 243902, Time: 2018-08-08 17:08:49.113466
Total Rows Read: 3400000, Paired Rows: 251234, Time: 2018-08-08 17:08:58.385641
Total Rows Read: 3500000, Paired Rows: 258124, Time: 2018-08-08 17:09:07.676911
Total Rows Read: 3600000, Paired Rows: 265210, Time: 2018-08-08 17:09:17.383272
Total Rows Read: 3700000, Paired Rows: 272252, Time: 2018-08-08 17:09:26.855941
Total Rows Read: 3800000, Paired Rows: 278963, Time: 2018-08-08 17:09:36.178252
Total Rows Read: 3900000, Paired Rows: 286324, Time: 2018-08-08 17:09:45.284886
Total Rows Read: 4000000, Paired Rows: 294129, Time: 2018-08-08 17:09:54.882439
Cleanin up!
Total Rows Read: 4100000, Paired Rows: 299538, Time: 2018-08-08 17:10:10.004604
Total Rows Read: 4200000, Paired Rows: 306191, Time: 2018-08-08 17:10:19.803814
Total Rows Read: 4300000, Paired Rows: 313162, Time: 2018-08-08 17:10:29.429429
Total Rows Read: 4400000, Paired Rows: 320235, Time: 2018-08-08 17:10:39.094896
Total Rows Read: 4500000, Paired Rows: 327148, Time: 2018-08-08 17:10:48.684988
Total Rows Read: 4600000, Paired Rows: 334544, Time: 2018-08-08 17:10:58.281550
Total Rows Read: 4700000, Paired Rows: 342592, Time: 2018-08-08 17:11:07.828914
Total Rows Read: 4800000, Paired Rows: 350431, Time: 2018-08-08 17:11:17.328416
Total Rows Read: 4900000, Paired Rows: 358565, Time: 2018-08-08 17:11:26.825090
Total Rows Read: 5000000, Paired Rows: 366831, Time: 2018-08-08 17:11:36.313032
Cleanin up!
Total Rows Read: 5100000, Paired Rows: 373056, Time: 2018-08-08 17:11:52.336174
Total Rows Read: 5200000, Paired Rows: 380715, Time: 2018-08-08 17:12:01.779120
Total Rows Read: 5300000, Paired Rows: 388747, Time: 2018-08-08 17:12:11.312475
Total Rows Read: 5400000, Paired Rows: 396873, Time: 2018-08-08 17:12:20.888699
Total Rows Read: 5500000, Paired Rows: 405288, Time: 2018-08-08 17:12:30.617899
Total Rows Read: 5600000, Paired Rows: 413538, Time: 2018-08-08 17:12:40.280190
Total Rows Read: 5700000, Paired Rows: 421986, Time: 2018-08-08 17:12:49.885370
Total Rows Read: 5800000, Paired Rows: 430460, Time: 2018-08-08 17:12:59.508174
Total Rows Read: 5900000, Paired Rows: 438995, Time: 2018-08-08 17:13:08.990479
Total Rows Read: 6000000, Paired Rows: 447151, Time: 2018-08-08 17:13:18.406836
Cleanin up!
Total Rows Read: 6100000, Paired Rows: 453313, Time: 2018-08-08 17:13:35.244212
Total Rows Read: 6200000, Paired Rows: 460766, Time: 2018-08-08 17:13:45.322652
Total Rows Read: 6300000, Paired Rows: 468319, Time: 2018-08-08 17:13:54.793181
Total Rows Read: 6400000, Paired Rows: 476536, Time: 2018-08-08 17:14:05.348429
Total Rows Read: 6500000, Paired Rows: 484978, Time: 2018-08-08 17:14:15.363070
Total Rows Read: 6600000, Paired Rows: 493225, Time: 2018-08-08 17:14:25.798299
Total Rows Read: 6700000, Paired Rows: 501485, Time: 2018-08-08 17:14:35.739332
Total Rows Read: 6800000, Paired Rows: 509313, Time: 2018-08-08 17:14:45.559585
Total Rows Read: 6900000, Paired Rows: 517121, Time: 2018-08-08 17:14:54.933716
Total Rows Read: 7000000, Paired Rows: 524934, Time: 2018-08-08 17:15:04.356283
Cleanin up!
Total Rows Read: 7100000, Paired Rows: 530683, Time: 2018-08-08 17:15:21.567787
Total Rows Read: 7200000, Paired Rows: 537716, Time: 2018-08-08 17:15:31.022868
Total Rows Read: 7300000, Paired Rows: 545108, Time: 2018-08-08 17:15:40.309849
Total Rows Read: 7400000, Paired Rows: 552646, Time: 2018-08-08 17:15:50.186498
Total Rows Read: 7500000, Paired Rows: 560291, Time: 2018-08-08 17:15:59.496164
Total Rows Read: 7600000, Paired Rows: 567822, Time: 2018-08-08 17:16:08.939243
Total Rows Read: 7700000, Paired Rows: 575279, Time: 2018-08-08 17:16:18.666273
Total Rows Read: 7800000, Paired Rows: 582548, Time: 2018-08-08 17:16:28.331378
Total Rows Read: 7900000, Paired Rows: 589766, Time: 2018-08-08 17:16:37.907577
Total Rows Read: 8000000, Paired Rows: 597261, Time: 2018-08-08 17:16:47.507727
Cleanin up!
Total Rows Read: 8100000, Paired Rows: 602917, Time: 2018-08-08 17:17:05.612935
Total Rows Read: 8200000, Paired Rows: 610169, Time: 2018-08-08 17:17:15.098004
Total Rows Read: 8300000, Paired Rows: 617841, Time: 2018-08-08 17:17:25.038709
Total Rows Read: 8400000, Paired Rows: 625590, Time: 2018-08-08 17:17:34.470975
Total Rows Read: 8500000, Paired Rows: 633741, Time: 2018-08-08 17:17:44.281628
Total Rows Read: 8600000, Paired Rows: 641985, Time: 2018-08-08 17:17:53.929662
Total Rows Read: 8700000, Paired Rows: 650429, Time: 2018-08-08 17:18:03.540866
Total Rows Read: 8800000, Paired Rows: 658912, Time: 2018-08-08 17:18:13.073504
Total Rows Read: 8900000, Paired Rows: 667558, Time: 2018-08-08 17:18:22.617413
Total Rows Read: 9000000, Paired Rows: 676327, Time: 2018-08-08 17:18:32.044280
Cleanin up!
Total Rows Read: 9100000, Paired Rows: 682600, Time: 2018-08-08 17:18:50.674144
Total Rows Read: 9200000, Paired Rows: 690129, Time: 2018-08-08 17:19:00.786782
Total Rows Read: 9300000, Paired Rows: 698232, Time: 2018-08-08 17:19:10.099673
Total Rows Read: 9400000, Paired Rows: 706280, Time: 2018-08-08 17:19:19.850965
Total Rows Read: 9500000, Paired Rows: 714586, Time: 2018-08-08 17:19:29.663765
Total Rows Read: 9600000, Paired Rows: 722877, Time: 2018-08-08 17:19:39.745871
s-NO PARENT disk I/O error
Total Rows Read: 9700000, Paired Rows: 731026, Time: 2018-08-08 17:19:49.328960
Total Rows Read: 9800000, Paired Rows: 739049, Time: 2018-08-08 17:19:58.925029
Total Rows Read: 9900000, Paired Rows: 747512, Time: 2018-08-08 17:20:08.456284
Total Rows Read: 10000000, Paired Rows: 755984, Time: 2018-08-08 17:20:17.744348
Cleanin up!
Total Rows Read: 10100000, Paired Rows: 761903, Time: 2018-08-08 17:20:37.363266

Total Rows Read: 10200000, Paired Rows: 768756, Time: 2018-08-08 17:20:46.727987
Total Rows Read: 10300000, Paired Rows: 775713, Time: 2018-08-08 17:20:55.753329
Total Rows Read: 10400000, Paired Rows: 782764, Time: 2018-08-08 17:21:05.307248
Total Rows Read: 10500000, Paired Rows: 790226, Time: 2018-08-08 17:21:14.833794
Total Rows Read: 10600000, Paired Rows: 797739, Time: 2018-08-08 17:21:24.266693
Total Rows Read: 10700000, Paired Rows: 805652, Time: 2018-08-08 17:21:33.817462
Total Rows Read: 10800000, Paired Rows: 813740, Time: 2018-08-08 17:21:43.298900
Total Rows Read: 10900000, Paired Rows: 821608, Time: 2018-08-08 17:21:53.495926
Total Rows Read: 11000000, Paired Rows: 829839, Time: 2018-08-08 17:22:03.965616
Cleanin up!
Total Rows Read: 11100000, Paired Rows: 835689, Time: 2018-08-08 17:22:25.420986
Total Rows Read: 11200000, Paired Rows: 842360, Time: 2018-08-08 17:22:35.028785
Total Rows Read: 11300000, Paired Rows: 849113, Time: 2018-08-08 17:22:45.259503
Total Rows Read: 11400000, Paired Rows: 856051, Time: 2018-08-08 17:22:55.667097
Total Rows Read: 11500000, Paired Rows: 863575, Time: 2018-08-08 17:23:05.470646
Total Rows Read: 11600000, Paired Rows: 871344, Time: 2018-08-08 17:23:14.955177
Total Rows Read: 11700000, Paired Rows: 879466, Time: 2018-08-08 17:23:24.840985
Total Rows Read: 11800000, Paired Rows: 888010, Time: 2018-08-08 17:23:35.121068
Total Rows Read: 11900000, Paired Rows: 896685, Time: 2018-08-08 17:23:45.000811
Total Rows Read: 12000000, Paired Rows: 905313, Time: 2018-08-08 17:23:54.710220
Cleanin up!
Total Rows Read: 12100000, Paired Rows: 911700, Time: 2018-08-08 17:24:16.543958
Total Rows Read: 12200000, Paired Rows: 919635, Time: 2018-08-08 17:24:27.522077
Total Rows Read: 12300000, Paired Rows: 927900, Time: 2018-08-08 17:24:37.979928
Total Rows Read: 12400000, Paired Rows: 936480, Time: 2018-08-08 17:24:48.331075
Total Rows Read: 12500000, Paired Rows: 944897, Time: 2018-08-08 17:24:58.414450
Total Rows Read: 12600000, Paired Rows: 953483, Time: 2018-08-08 17:25:08.541870
Total Rows Read: 12700000, Paired Rows: 962231, Time: 2018-08-08 17:25:18.513976
Total Rows Read: 12800000, Paired Rows: 970796, Time: 2018-08-08 17:25:28.614242
Total Rows Read: 12900000, Paired Rows: 979345, Time: 2018-08-08 17:25:38.227498
Total Rows Read: 13000000, Paired Rows: 987795, Time: 2018-08-08 17:25:47.905849
Cleanin up!
Total Rows Read: 13100000, Paired Rows: 993965, Time: 2018-08-08 17:26:10.544793
Total Rows Read: 13200000, Paired Rows: 1001463, Time: 2018-08-08 17:26:21.073658
Total Rows Read: 13300000, Paired Rows: 1009400, Time: 2018-08-08 17:26:31.709642
Total Rows Read: 13400000, Paired Rows: 1017151, Time: 2018-08-08 17:26:42.251863
Total Rows Read: 13500000, Paired Rows: 1024867, Time: 2018-08-08 17:26:52.391313
Total Rows Read: 13600000, Paired Rows: 1032587, Time: 2018-08-08 17:27:02.623972
Total Rows Read: 13700000, Paired Rows: 1040347, Time: 2018-08-08 17:27:12.342218
Total Rows Read: 13800000, Paired Rows: 1048096, Time: 2018-08-08 17:27:22.120437
Total Rows Read: 13900000, Paired Rows: 1055739, Time: 2018-08-08 17:27:31.826412
Total Rows Read: 14000000, Paired Rows: 1063535, Time: 2018-08-08 17:27:41.651814
Cleanin up!
Total Rows Read: 14100000, Paired Rows: 1069308, Time: 2018-08-08 17:28:03.888832
Total Rows Read: 14200000, Paired Rows: 1076326, Time: 2018-08-08 17:28:13.418074
Total Rows Read: 14300000, Paired Rows: 1083443, Time: 2018-08-08 17:28:23.807000
Total Rows Read: 14400000, Paired Rows: 1090507, Time: 2018-08-08 17:28:34.212722
Total Rows Read: 14500000, Paired Rows: 1097445, Time: 2018-08-08 17:28:44.216672
Total Rows Read: 14600000, Paired Rows: 1104705, Time: 2018-08-08 17:28:54.326250
Total Rows Read: 14700000, Paired Rows: 1112195, Time: 2018-08-08 17:29:04.614878
Total Rows Read: 14800000, Paired Rows: 1120070, Time: 2018-08-08 17:29:14.764834
Total Rows Read: 14900000, Paired Rows: 1128357, Time: 2018-08-08 17:29:24.402400
Total Rows Read: 15000000, Paired Rows: 1136739, Time: 2018-08-08 17:29:34.339842
Cleanin up!
Total Rows Read: 15100000, Paired Rows: 1143069, Time: 2018-08-08 17:29:58.542778
Total Rows Read: 15200000, Paired Rows: 1150857, Time: 2018-08-08 17:30:08.265532
Total Rows Read: 15300000, Paired Rows: 1159094, Time: 2018-08-08 17:30:18.294289
Total Rows Read: 15400000, Paired Rows: 1167343, Time: 2018-08-08 17:30:28.413149
Total Rows Read: 15500000, Paired Rows: 1175644, Time: 2018-08-08 17:30:38.964898
Total Rows Read: 15600000, Paired Rows: 1184058, Time: 2018-08-08 17:30:49.067968
Total Rows Read: 15700000, Paired Rows: 1192343, Time: 2018-08-08 17:30:58.333121
Total Rows Read: 15800000, Paired Rows: 1200897, Time: 2018-08-08 17:31:07.944287
Total Rows Read: 15900000, Paired Rows: 1209783, Time: 2018-08-08 17:31:18.084059
Total Rows Read: 16000000, Paired Rows: 1218067, Time: 2018-08-08 17:31:28.500346
Cleanin up!
Total Rows Read: 16100000, Paired Rows: 1224454, Time: 2018-08-08 17:31:53.204225
Total Rows Read: 16200000, Paired Rows: 1231793, Time: 2018-08-08 17:32:03.303685
Total Rows Read: 16300000, Paired Rows: 1238575, Time: 2018-08-08 17:32:12.773533
Total Rows Read: 16400000, Paired Rows: 1246565, Time: 2018-08-08 17:32:22.161883
Total Rows Read: 16500000, Paired Rows: 1254353, Time: 2018-08-08 17:32:31.636761
Total Rows Read: 16600000, Paired Rows: 1262011, Time: 2018-08-08 17:32:41.335658
Total Rows Read: 16700000, Paired Rows: 1269742, Time: 2018-08-08 17:32:51.184936

KeyboardInterrupt: